[package]
name = "rynth"
version = "0.1.0"
authors = ["Felipe Silveira <felipessilveira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
anyhow = "1.0.42"
clap = "2.33.3"