[package]
name = "rynth"
version = "0.1.0"
authors = ["Felipe Silveira <felipessilveira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.5"
anyhow = "1.0.56"
clap = "2.33.4"
hound = "3.4.0"